#!/usr/bin/env python
import random

alpha = ("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F")
mac = []
for i in range(12):
    mac.append(''.join([random.choice(alpha)]))
print "%s%s:%s%s:%s%s:%s%s:%s%s:%s%s" % (mac[0],mac[1],mac[2],mac[3],mac[4],mac[5],
                                         mac[6],mac[7],mac[8],mac[9],mac[10],mac[11])

