#!/usr/bin/python
import sys
import random
import string


def main(argv):
    print ''.join(random.choice(string.letters + string.digits) for _ in range(int(argv)))

if __name__ == '__main__':
    if len(sys.argv) > 1:
        main(sys.argv[1])
    else:
        main(12)

