#!/usr/bin/python
import sys
import random
import string
import numbers

def main(argv):
    try:
        num = int(argv)
    except ValueError:
        try:
            num = ord(argv)
        except TypeError:
            print "Does not accept unicode characters or multiple none number chars"
            sys.exit(1)

    print ''.join(random.choice(string.letters + string.digits) for _ in range(int(num)))

if __name__ == '__main__':
    if len(sys.argv) > 1:
        main(sys.argv[1])
    else:
        main(12)

