---
- hosts: all
  roles:
  - { role: geerlingguy.gitlab }

  vars: 
    gitlab_domain: gitlab.l.opentokix.com
    gitlab_external_url: "http://gitlab.l.opentokix.com"
    gitlab_git_data_dir: "/srv/gitlab/git-data"
    gitlab_backup_path: "/var/opt/gitlab/backups"
    gitlab_edition: "gitlab-ce"
    gitlab_version: ''
    gitlab_config_template: "gitlab.rb.j2" 
    gitlab_redirect_http_to_https: "true" 
    gitlab_ssl_certificate: "/etc/gitlab/ssl/{{ gitlab_domain }}.crt"
    gitlab_ssl_certificate_key: "/etc/gitlab/ssl/{{ gitlab_domain }}.key"
    gitlab_create_self_signed_cert: "true" 
    gitlab_self_signed_cert_subj: "/C=SE/ST=Stockholm/L=Stockholm/O=Hypercube/CN={{ gitlab_domain }}"
    gitlab_ldap_enabled: "false"
    gitlab_dependencies:
      - openssh-server
      - postfix
      - curl
      - openssl
      - tzdata
    gitlab_time_zone: "UTC"
    gitlab_backup_keep_time: "604800"
    gitlab_download_validate_certs: true
    gitlab_email_enabled: "false"
    gitlab_email_from: "gitlab@opentokix.com"
    gitlab_email_display_name: "Gitlab"
    gitlab_email_reply_to: "gitlab@opentokix.com"
    gitlab_nginx_listen_port: 8080
    gitlab_nginx_listen_https: "false"
    gitlab_default_theme: 2

